import Foundation

/// Renders a report as one self-contained HTML file.
///
/// Inline CSS, no external assets, no scripts — so it survives being emailed, dropped
/// into a ticket, or opened years later on a machine with no network. It is also the
/// only renderer: the PDF is produced by printing this HTML rather than by a second
/// builder, so the two formats cannot drift apart the way the CLI's separate HTML and
/// PDF builders can.
public enum HTMLReportBuilder {

    public static func build(_ report: DiagnosticReport, redacted: Bool = false) -> String {
        let report = redacted ? ReportRedaction.apply(to: report) : report
        var html = ""

        html += "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        html += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        html += "<title>DiagClean Report — \(escape(report.overview?.computerName ?? "Mac"))</title>"
        html += "<style>\(css)</style></head><body>"

        html += header(report, redacted: redacted)
        if report.includes(.overview) { html += overviewSection(report) }
        if report.includes(.hardware) { html += hardwareSection(report) }
        if report.includes(.storage) { html += storageSection(report) }
        if report.includes(.performance) { html += performanceSection(report) }
        if report.includes(.network) { html += networkSection(report) }
        if report.includes(.crashes) { html += crashesSection(report) }
        if report.includes(.software) { html += softwareSection(report) }
        html += failuresSection(report)

        html += "<footer>Generated by DiagClean on \(escape(timestamp(report.generatedAt)))</footer>"
        html += "</body></html>"
        return html
    }

    // MARK: - Sections

    private static func header(_ report: DiagnosticReport, redacted: Bool) -> String {
        var html = "<header><h1>Diagnostic Report</h1><p class=\"sub\">"
        html += escape(report.overview?.computerName ?? "This Mac")
        html += " · \(escape(timestamp(report.generatedAt)))</p>"
        if redacted {
            // Stated at the top, because a reader who does not know the report was
            // redacted will read "[redacted]" as a collection failure.
            html += "<p class=\"note\">Identifying details have been redacted from this report.</p>"
        }
        html += "</header>"
        return html
    }

    private static func overviewSection(_ report: DiagnosticReport) -> String {
        guard let overview = report.overview else { return missing(.overview) }
        return section("Overview", rows: [
            ("Computer", overview.computerName),
            ("Generated by", overview.userName),
            ("macOS", "\(overview.osVersion) (\(overview.osBuild))"),
            ("Uptime", duration(overview.uptime)),
        ])
    }

    private static func hardwareSection(_ report: DiagnosticReport) -> String {
        guard let hardware = report.hardware else { return missing(.hardware) }
        return section("Hardware", rows: [
            ("Model", hardware.model),
            ("Chip", hardware.chip),
            ("Cores", "\(hardware.coreCount)"),
            ("Memory", ByteFormat.string(Int64(hardware.memoryBytes))),
        ])
    }

    private static func storageSection(_ report: DiagnosticReport) -> String {
        guard !report.volumes.isEmpty else { return missing(.storage) }

        var html = "<section><h2>Storage</h2><table><thead><tr>"
        html += "<th>Volume</th><th>Capacity</th><th>Free</th><th>Used</th><th>SMART</th>"
        html += "</tr></thead><tbody>"

        for volume in report.volumes {
            let usedFraction = volume.totalBytes > 0
                ? Double(volume.totalBytes - volume.availableBytes) / Double(volume.totalBytes)
                : 0
            // A failing disk is the one line in a diagnostic report that means "replace
            // this machine now", so it is the one thing here allowed to shout.
            let smartClass = volume.smartStatus.isAlarming ? " class=\"bad\"" : ""

            html += "<tr>"
            html += "<td>\(escape(volume.name))</td>"
            html += "<td>\(escape(ByteFormat.string(volume.totalBytes)))</td>"
            html += "<td>\(escape(ByteFormat.string(volume.availableBytes)))</td>"
            html += "<td>\(Int(usedFraction * 100))%</td>"
            html += "<td\(smartClass)>\(escape(volume.smartStatus.label))</td>"
            html += "</tr>"
        }

        return html + "</tbody></table></section>"
    }

    private static func performanceSection(_ report: DiagnosticReport) -> String {
        guard let status = report.performance else { return missing(.performance) }
        var rows: [(String, String)] = [
            ("CPU", String(format: "%.0f%%", status.cpuPercent)),
            ("Memory used", "\(ByteFormat.string(Int64(status.memory.usedBytes))) of \(ByteFormat.string(Int64(status.memory.totalBytes)))"),
        ]
        if status.memory.swapUsedBytes > 0 {
            rows.append(("Swap in use", ByteFormat.string(Int64(status.memory.swapUsedBytes))))
        }
        if let load = status.loadAverage {
            rows.append(("Load average", String(format: "%.2f · %.2f · %.2f", load.oneMinute, load.fiveMinutes, load.fifteenMinutes)))
        }
        if let battery = status.battery {
            rows.append(("Battery", "\(battery.percent)% · \(battery.isPluggedIn ? "plugged in" : "on battery")"))
        }
        return section("Performance", rows: rows)
    }

    private static func networkSection(_ report: DiagnosticReport) -> String {
        guard !report.interfaces.isEmpty else { return missing(.network) }

        var html = "<section><h2>Network</h2><table><thead><tr>"
        html += "<th>Interface</th><th>Status</th><th>Addresses</th><th>MAC</th>"
        html += "</tr></thead><tbody>"

        for interface in report.interfaces {
            html += "<tr>"
            html += "<td>\(escape(interface.name))</td>"
            html += "<td>\(interface.isUp ? "Up" : "Down")</td>"
            // Escape each address first, then join with real markup. Escaping the
            // joined string would turn the separator into a literal "<br>" on the page.
            let addresses = interface.ipAddresses.map(escape).joined(separator: "<br>")
            html += "<td>\(addresses.isEmpty ? "—" : addresses)</td>"
            html += "<td>\(escape(interface.macAddress ?? "—"))</td>"
            html += "</tr>"
        }

        html += "</tbody></table>"
        if !report.dnsServers.isEmpty {
            html += "<p class=\"empty\">DNS servers: \(report.dnsServers.map(escape).joined(separator: ", "))</p>"
        }
        return html + "</section>"
    }

    private static func crashesSection(_ report: DiagnosticReport) -> String {
        guard !report.crashes.isEmpty else {
            return "<section><h2>Recent Crashes</h2><p class=\"empty\">No crashes recorded in the last 14 days.</p></section>"
        }

        var html = "<section><h2>Recent Crashes</h2><table><thead><tr><th>Application</th><th>When</th></tr></thead><tbody>"
        for crash in report.crashes.prefix(50) {
            html += "<tr><td>\(escape(crash.appName))</td><td>\(escape(timestamp(crash.date)))</td></tr>"
        }
        html += "</tbody></table>"
        if report.crashes.count > 50 {
            html += "<p class=\"empty\">\(report.crashes.count - 50) older entries not listed.</p>"
        }
        return html + "</section>"
    }

    private static func softwareSection(_ report: DiagnosticReport) -> String {
        guard !report.software.isEmpty else { return missing(.software) }

        var html = "<section><h2>Installed Software</h2>"
        html += "<p class=\"empty\">\(report.software.count) applications</p>"
        html += "<table><thead><tr><th>Name</th><th>Version</th><th>Size</th></tr></thead><tbody>"

        for app in report.software.sorted(by: { $0.name.lowercased() < $1.name.lowercased() }) {
            html += "<tr>"
            html += "<td>\(escape(app.name))</td>"
            html += "<td>\(escape(app.version.isEmpty ? "—" : app.version))</td>"
            html += "<td>\(escape(ByteFormat.string(app.sizeBytes)))</td>"
            html += "</tr>"
        }

        return html + "</tbody></table></section>"
    }

    private static func failuresSection(_ report: DiagnosticReport) -> String {
        guard !report.failures.isEmpty else { return "" }

        var html = "<section><h2>Could not be collected</h2><table><thead><tr><th>Section</th><th>Reason</th></tr></thead><tbody>"
        for failure in report.failures {
            html += "<tr><td>\(escape(failure.section.title))</td><td>\(escape(failure.reason))</td></tr>"
        }
        return html + "</tbody></table></section>"
    }

    // MARK: - Building blocks

    private static func section(_ title: String, rows: [(String, String)]) -> String {
        var html = "<section><h2>\(escape(title))</h2><table><tbody>"
        for (label, value) in rows {
            html += "<tr><th class=\"label\">\(escape(label))</th><td>\(escape(value))</td></tr>"
        }
        return html + "</tbody></table></section>"
    }

    private static func missing(_ section: ReportSection) -> String {
        "<section><h2>\(escape(section.title))</h2><p class=\"empty\">Not available on this machine.</p></section>"
    }

    /// Everything user-supplied goes through here.
    ///
    /// Application names, volume names and computer names are all attacker-influenced in
    /// the sense that matters: somebody can install an app called `<script>` or name a
    /// disk with a quote, and the report would then be malformed or worse in whatever
    /// browser eventually opens it. Escaping is not optional in a document built by
    /// string concatenation.
    static func escape(_ value: String) -> String {
        var escaped = ""
        escaped.reserveCapacity(value.count)
        for character in value {
            switch character {
            case "&": escaped += "&amp;"
            case "<": escaped += "&lt;"
            case ">": escaped += "&gt;"
            case "\"": escaped += "&quot;"
            case "'": escaped += "&#39;"
            default: escaped.append(character)
            }
        }
        return escaped
    }

    private static func timestamp(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: date)
    }

    private static func duration(_ interval: TimeInterval) -> String {
        let days = Int(interval) / 86_400
        let hours = (Int(interval) % 86_400) / 3600
        let minutes = (Int(interval) % 3600) / 60
        if days > 0 { return "\(days)d \(hours)h" }
        if hours > 0 { return "\(hours)h \(minutes)m" }
        return "\(minutes)m"
    }

    /// Light, printable, and legible on paper. The report is read in a browser and then
    /// very often printed to PDF and attached to a ticket, so it is designed for ink
    /// rather than for the dark interface that generated it.
    private static let css = """
    * { box-sizing: border-box; }
    body {
      font: 13px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
      color: #1c1c1e; background: #fff; margin: 0; padding: 32px;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    header { border-bottom: 2px solid #1c1c1e; padding-bottom: 12px; margin-bottom: 24px; }
    h1 { font-size: 22px; margin: 0 0 4px; font-weight: 600; }
    h2 { font-size: 15px; margin: 0 0 8px; font-weight: 600; }
    .sub { margin: 0; color: #6b6b70; }
    .note { margin: 8px 0 0; padding: 6px 10px; background: #f2f2f4; border-left: 3px solid #6b6b70; color: #3a3a3c; }
    section { margin-bottom: 28px; page-break-inside: avoid; }
    table { border-collapse: collapse; width: 100%; }
    th, td { text-align: left; padding: 5px 8px; border-bottom: 1px solid #e5e5e7; vertical-align: top; }
    thead th { border-bottom: 1px solid #1c1c1e; font-weight: 600; }
    th.label { width: 160px; color: #6b6b70; font-weight: 400; }
    td.bad { color: #b3261e; font-weight: 600; }
    .empty { color: #6b6b70; margin: 0 0 8px; }
    footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e5e7; color: #6b6b70; }
    @media print { body { padding: 0; } }
    """
}
