using System.Net;
using System.Text;
using DiagClean.Core.Models;

namespace DiagClean.Core.Reporting;

/// <summary>
/// Renders a <see cref="DiagnosticReport"/> as a single self-contained HTML file —
/// inline CSS only, no external assets — so it can be emailed or dropped into a ticket
/// as-is and still render correctly.
/// </summary>
public static class HtmlReportBuilder
{
    public static string Build(DiagnosticReport report)
    {
        var sb = new StringBuilder();

        sb.Append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.Append("<title>DiagClean Report - ").Append(Enc(report.MachineName)).Append("</title>");
        sb.Append("<style>").Append(Css).Append("</style></head><body>");

        sb.Append("<div class=\"page\">");
        AppendHeader(sb, report);
        AppendHardware(sb, report.Hardware);
        AppendDisks(sb, report.Disks);
        AppendPerformance(sb, report.Performance);
        AppendNetwork(sb, report.NetworkAdapters);
        AppendEventLog(sb, report.EventLogEntries);
        AppendSoftware(sb, report.InstalledSoftware);
        AppendCollectorErrors(sb, report.CollectorErrors);
        sb.Append("<div class=\"footer\">Generated by DiagClean &middot; ")
          .Append(Enc(report.GeneratedAt.ToString("u")))
          .Append("</div>");
        sb.Append("</div>"); // .page

        sb.Append("</body></html>");
        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb, DiagnosticReport report)
    {
        sb.Append("<div class=\"header\">");
        sb.Append("<h1>DiagClean Diagnostic Report</h1>");
        sb.Append("<div class=\"meta\">");
        sb.Append("<span><strong>Machine:</strong> ").Append(Enc(report.MachineName)).Append("</span>");
        sb.Append("<span><strong>Generated:</strong> ").Append(Enc(report.GeneratedAt.ToString("f"))).Append("</span>");
        sb.Append("<span><strong>Collected by:</strong> ").Append(Enc(report.CollectedBy)).Append("</span>");
        sb.Append("</div></div>");
    }

    private static void AppendHardware(StringBuilder sb, HardwareInfo? hw)
    {
        sb.Append(SectionStart("Hardware Summary"));
        if (hw is null)
        {
            sb.Append(EmptyNotice("Hardware data unavailable."));
        }
        else
        {
            sb.Append("<div class=\"kv-grid\">");
            AppendKv(sb, "CPU", hw.CpuName);
            AppendKv(sb, "Cores / Logical Processors", $"{hw.CpuCores} / {hw.CpuLogicalProcessors}");
            AppendKv(sb, "RAM", $"{hw.TotalRamGb:0.#} GB");
            AppendKv(sb, "Motherboard", $"{hw.MotherboardManufacturer} {hw.MotherboardModel}".Trim());
            AppendKv(sb, "BIOS Version", hw.BiosVersion);
            AppendKv(sb, "GPU", hw.GpuNames.Count > 0 ? string.Join(", ", hw.GpuNames) : "-");
            sb.Append("</div>");
        }
        sb.Append(SectionEnd());
    }

    private static void AppendDisks(StringBuilder sb, IReadOnlyList<DiskInfo> disks)
    {
        sb.Append(SectionStart("Disk Health"));
        if (disks.Count == 0)
        {
            sb.Append(EmptyNotice("No disk data collected."));
        }
        else
        {
            sb.Append("<table><thead><tr><th>Device</th><th>Model</th><th>Type</th><th>Size</th><th>Free</th><th>SMART Status</th></tr></thead><tbody>");
            foreach (var d in disks)
            {
                sb.Append("<tr>");
                sb.Append("<td>").Append(Enc(d.DeviceId)).Append("</td>");
                sb.Append("<td>").Append(Enc(d.Model)).Append("</td>");
                sb.Append("<td>").Append(Enc(d.MediaType)).Append("</td>");
                sb.Append("<td>").Append($"{d.SizeGb:0.#} GB").Append("</td>");
                sb.Append("<td>").Append($"{d.FreeGb:0.#} GB").Append("</td>");
                sb.Append("<td>").Append(Badge(SmartBadgeClass(d.SmartStatus), d.SmartStatus.ToString()));
                if (!string.IsNullOrWhiteSpace(d.SmartDetail))
                {
                    sb.Append("<div class=\"sub\">").Append(Enc(d.SmartDetail)).Append("</div>");
                }
                sb.Append("</td>");
                sb.Append("</tr>");
            }
            sb.Append("</tbody></table>");
        }
        sb.Append(SectionEnd());
    }

    private static void AppendPerformance(StringBuilder sb, PerformanceSnapshot? perf)
    {
        sb.Append(SectionStart("Performance Snapshot"));
        if (perf is null)
        {
            sb.Append(EmptyNotice("Performance data unavailable."));
        }
        else
        {
            sb.Append("<div class=\"kv-grid\">");
            AppendKv(sb, "CPU Load", $"{perf.CpuLoadPercent:0.#}%");
            AppendKv(sb, "Memory Used", $"{perf.MemoryUsedPercent:0.#}%");
            AppendKv(sb, "System Uptime", $"{perf.SystemUptimeHours:0.#} hours");
            AppendKv(sb, "Recent App Crashes", perf.RecentApplicationCrashCount.ToString());
            sb.Append("</div>");
        }
        sb.Append(SectionEnd());
    }

    private static void AppendNetwork(StringBuilder sb, IReadOnlyList<NetworkAdapterInfo> adapters)
    {
        sb.Append(SectionStart("Network Configuration"));
        if (adapters.Count == 0)
        {
            sb.Append(EmptyNotice("No network adapters found."));
        }
        else
        {
            foreach (var a in adapters)
            {
                sb.Append("<div class=\"adapter-card\">");
                sb.Append("<div class=\"adapter-title\">").Append(Enc(a.Name));
                sb.Append(Badge(a.IsUp ? "ok" : "muted", a.IsUp ? "Up" : "Down"));
                sb.Append("</div>");
                sb.Append("<div class=\"kv-grid\">");
                AppendKv(sb, "Description", a.Description);
                AppendKv(sb, "MAC", a.MacAddress);
                AppendKv(sb, "IP Address(es)", a.IpAddresses.Count > 0 ? string.Join(", ", a.IpAddresses) : "-");
                AppendKv(sb, "DNS Servers", a.DnsServers.Count > 0 ? string.Join(", ", a.DnsServers) : "-");
                AppendKv(sb, "Gateway", a.Gateway ?? "-");
                sb.Append("</div></div>");
            }
        }
        sb.Append(SectionEnd());
    }

    private static void AppendEventLog(StringBuilder sb, IReadOnlyList<EventLogEntryInfo> entries)
    {
        sb.Append(SectionStart($"Recent Event Log Errors &amp; Warnings ({entries.Count})"));
        if (entries.Count == 0)
        {
            sb.Append(EmptyNotice("No recent errors or warnings found."));
        }
        else
        {
            sb.Append("<table><thead><tr><th>Time</th><th>Log</th><th>Source</th><th>Severity</th><th>Event ID</th><th>Message</th></tr></thead><tbody>");
            foreach (var e in entries.OrderByDescending(e => e.TimeGenerated))
            {
                sb.Append("<tr>");
                sb.Append("<td class=\"nowrap\">").Append(Enc(e.TimeGenerated.ToString("g"))).Append("</td>");
                sb.Append("<td>").Append(Enc(e.LogName)).Append("</td>");
                sb.Append("<td>").Append(Enc(e.Source)).Append("</td>");
                sb.Append("<td>").Append(Badge(SeverityBadgeClass(e.Severity), e.Severity.ToString())).Append("</td>");
                sb.Append("<td>").Append(e.EventId).Append("</td>");
                sb.Append("<td class=\"msg\">").Append(Enc(Truncate(e.Message, 400))).Append("</td>");
                sb.Append("</tr>");
            }
            sb.Append("</tbody></table>");
        }
        sb.Append(SectionEnd());
    }

    private static void AppendSoftware(StringBuilder sb, IReadOnlyList<InstalledSoftware> software)
    {
        sb.Append(SectionStart($"Installed Software ({software.Count})"));
        if (software.Count == 0)
        {
            sb.Append(EmptyNotice("No installed software data collected."));
        }
        else
        {
            sb.Append("<table><thead><tr><th>Name</th><th>Version</th><th>Publisher</th><th>Installed</th></tr></thead><tbody>");
            foreach (var s in software.OrderBy(s => s.Name, StringComparer.OrdinalIgnoreCase))
            {
                sb.Append("<tr>");
                sb.Append("<td>").Append(Enc(s.Name)).Append("</td>");
                sb.Append("<td>").Append(Enc(s.Version)).Append("</td>");
                sb.Append("<td>").Append(Enc(s.Publisher)).Append("</td>");
                sb.Append("<td>").Append(s.InstallDate?.ToString("yyyy-MM-dd") ?? "-").Append("</td>");
                sb.Append("</tr>");
            }
            sb.Append("</tbody></table>");
        }
        sb.Append(SectionEnd());
    }

    private static void AppendCollectorErrors(StringBuilder sb, IReadOnlyList<CollectorError> errors)
    {
        if (errors.Count == 0)
        {
            return;
        }

        sb.Append(SectionStart("Collection Notices"));
        sb.Append("<div class=\"notice-box\">This report may be incomplete &mdash; the following collectors could not finish:</div>");
        sb.Append("<ul class=\"error-list\">");
        foreach (var e in errors)
        {
            sb.Append("<li><strong>").Append(Enc(e.CollectorName)).Append(":</strong> ").Append(Enc(e.Message)).Append("</li>");
        }
        sb.Append("</ul>");
        sb.Append(SectionEnd());
    }

    private static void AppendKv(StringBuilder sb, string key, string value)
    {
        sb.Append("<div class=\"kv\"><span class=\"k\">").Append(Enc(key)).Append("</span><span class=\"v\">")
          .Append(string.IsNullOrWhiteSpace(value) ? "-" : Enc(value)).Append("</span></div>");
    }

    private static string SectionStart(string title) =>
        $"<section class=\"card\"><h2>{title}</h2>";

    private static string SectionEnd() => "</section>";

    private static string EmptyNotice(string text) => $"<p class=\"empty\">{Enc(text)}</p>";

    private static string Badge(string cssClass, string text) =>
        $"<span class=\"badge {cssClass}\">{Enc(text)}</span>";

    private static string SmartBadgeClass(SmartStatus status) => status switch
    {
        SmartStatus.Healthy => "ok",
        SmartStatus.Warning => "warn",
        SmartStatus.Failing => "bad",
        _ => "muted"
    };

    private static string SeverityBadgeClass(EventLogSeverity severity) => severity switch
    {
        EventLogSeverity.Warning => "warn",
        EventLogSeverity.Error => "bad",
        EventLogSeverity.Critical => "bad",
        _ => "muted"
    };

    private static string Truncate(string text, int maxLength) =>
        text.Length <= maxLength ? text : text[..maxLength] + "...";

    private static string Enc(string? text) => WebUtility.HtmlEncode(text ?? "");

    private const string Css = """
        :root {
            color-scheme: light;
            --bg: #f5f6f8;
            --card-bg: #ffffff;
            --border: #e2e4e9;
            --text: #1c1f26;
            --text-muted: #6b7280;
            --accent: #2f6feb;
            --ok-bg: #e6f6ec; --ok-fg: #1a7f4a;
            --warn-bg: #fff4e0; --warn-fg: #92600a;
            --bad-bg: #fdeaea; --bad-fg: #b3261e;
            --muted-bg: #eef0f3; --muted-fg: #5b6270;
        }
        * { box-sizing: border-box; }
        body {
            margin: 0; padding: 32px 16px;
            background: var(--bg); color: var(--text);
            font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            font-size: 14px; line-height: 1.5;
        }
        .page { max-width: 960px; margin: 0 auto; }
        .header { margin-bottom: 24px; }
        .header h1 { font-size: 22px; margin: 0 0 8px; }
        .meta { display: flex; flex-wrap: wrap; gap: 16px; color: var(--text-muted); font-size: 13px; }
        .card {
            background: var(--card-bg); border: 1px solid var(--border); border-radius: 10px;
            padding: 20px 24px; margin-bottom: 16px;
        }
        .card h2 { font-size: 15px; margin: 0 0 14px; text-transform: uppercase; letter-spacing: .04em; color: var(--text-muted); }
        .kv-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 10px 24px; }
        .kv { display: flex; justify-content: space-between; gap: 12px; border-bottom: 1px solid var(--border); padding-bottom: 6px; }
        .kv .k { color: var(--text-muted); }
        .kv .v { font-weight: 500; text-align: right; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; }
        th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--border); vertical-align: top; }
        th { color: var(--text-muted); font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: .03em; }
        tr:last-child td { border-bottom: none; }
        td.nowrap { white-space: nowrap; }
        td.msg { color: var(--text); max-width: 420px; }
        .sub { font-size: 12px; color: var(--text-muted); margin-top: 2px; }
        .badge {
            display: inline-block; padding: 2px 9px; border-radius: 999px;
            font-size: 12px; font-weight: 600;
        }
        .badge.ok { background: var(--ok-bg); color: var(--ok-fg); }
        .badge.warn { background: var(--warn-bg); color: var(--warn-fg); }
        .badge.bad { background: var(--bad-bg); color: var(--bad-fg); }
        .badge.muted { background: var(--muted-bg); color: var(--muted-fg); }
        .adapter-card { border: 1px solid var(--border); border-radius: 8px; padding: 14px 16px; margin-bottom: 12px; }
        .adapter-card:last-child { margin-bottom: 0; }
        .adapter-title { font-weight: 600; margin-bottom: 10px; display: flex; align-items: center; gap: 8px; }
        .empty { color: var(--text-muted); font-style: italic; margin: 0; }
        .notice-box { background: var(--warn-bg); color: var(--warn-fg); padding: 10px 14px; border-radius: 8px; margin-bottom: 10px; }
        .error-list { margin: 0; padding-left: 20px; color: var(--text-muted); }
        .footer { text-align: center; color: var(--text-muted); font-size: 12px; margin-top: 24px; }
        """;
}
